# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readInn_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 902)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fileNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 93, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 77, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 41, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 158, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 93, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 77, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 41, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 158, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 93, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 77, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 41, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 31, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.fileNameEdit.setPalette(palette)
        self.fileNameEdit.setObjectName("fileNameEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileNameEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileDateEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileDateEdit.setObjectName("fileDateEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fileDateEdit)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sensorFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sensorFileEdit.setObjectName("sensorFileEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sensorFileEdit)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.calibrationFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.calibrationFileEdit.setObjectName("calibrationFileEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calibrationFileEdit)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.scanAngleFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.scanAngleFileEdit.setObjectName("scanAngleFileEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scanAngleFileEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.elevationFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.elevationFileEdit.setObjectName("elevationFileEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.elevationFileEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.slopeFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.slopeFileEdit.setObjectName("slopeFileEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.slopeFileEdit)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.aspectFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.aspectFileEdit.setObjectName("aspectFileEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.aspectFileEdit)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.skyviewFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.skyviewFileEdit.setObjectName("skyviewFileEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.skyviewFileEdit)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.atmDatabaseCombo = QtWidgets.QComboBox(self.centralwidget)
        self.atmDatabaseCombo.setObjectName("atmDatabaseCombo")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.atmDatabaseCombo)
        self.wv830window1Edit = QtWidgets.QTabWidget(self.centralwidget)
        self.wv830window1Edit.setObjectName("wv830window1Edit")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.solarZenithEdit = QtWidgets.QLineEdit(self.tab)
        self.solarZenithEdit.setObjectName("solarZenithEdit")
        self.gridLayout.addWidget(self.solarZenithEdit, 0, 2, 1, 1)
        self.solarAzimuthEdit = QtWidgets.QLineEdit(self.tab)
        self.solarAzimuthEdit.setObjectName("solarAzimuthEdit")
        self.gridLayout.addWidget(self.solarAzimuthEdit, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 5, 0, 1, 1)
        self.tempGradEdit = QtWidgets.QLineEdit(self.tab)
        self.tempGradEdit.setObjectName("tempGradEdit")
        self.gridLayout.addWidget(self.tempGradEdit, 4, 2, 1, 1)
        self.refEleEdit = QtWidgets.QLineEdit(self.tab)
        self.refEleEdit.setObjectName("refEleEdit")
        self.gridLayout.addWidget(self.refEleEdit, 3, 2, 1, 1)
        self.wvpEdit = QtWidgets.QLineEdit(self.tab)
        self.wvpEdit.setObjectName("wvpEdit")
        self.gridLayout.addWidget(self.wvpEdit, 5, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 4, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 6, 0, 1, 1)
        self.aTempEdit = QtWidgets.QLineEdit(self.tab)
        self.aTempEdit.setObjectName("aTempEdit")
        self.gridLayout.addWidget(self.aTempEdit, 2, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 3, 0, 1, 1)
        self.scaleHeightEdit = QtWidgets.QLineEdit(self.tab)
        self.scaleHeightEdit.setObjectName("scaleHeightEdit")
        self.gridLayout.addWidget(self.scaleHeightEdit, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.wv830window1Edit.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.visibilityEdit = QtWidgets.QLineEdit(self.tab_3)
        self.visibilityEdit.setObjectName("visibilityEdit")
        self.gridLayout_2.addWidget(self.visibilityEdit, 4, 1, 1, 1)
        self.scaleFactorEdit = QtWidgets.QLineEdit(self.tab_3)
        self.scaleFactorEdit.setObjectName("scaleFactorEdit")
        self.gridLayout_2.addWidget(self.scaleFactorEdit, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.adjacencyRangeEdit = QtWidgets.QLineEdit(self.tab_3)
        self.adjacencyRangeEdit.setObjectName("adjacencyRangeEdit")
        self.gridLayout_2.addWidget(self.adjacencyRangeEdit, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 12, 1, 1, 1)
        self.pixelSizeEdit = QtWidgets.QLineEdit(self.tab_3)
        self.pixelSizeEdit.setObjectName("pixelSizeEdit")
        self.gridLayout_2.addWidget(self.pixelSizeEdit, 0, 1, 1, 1)
        self.gainEdit = QtWidgets.QLineEdit(self.tab_3)
        self.gainEdit.setObjectName("gainEdit")
        self.gridLayout_2.addWidget(self.gainEdit, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab_3)
        self.label_74.setObjectName("label_74")
        self.gridLayout_2.addWidget(self.label_74, 11, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab_3)
        self.label_73.setObjectName("label_73")
        self.gridLayout_2.addWidget(self.label_73, 10, 0, 1, 1)
        self.waterEmissEdit = QtWidgets.QLineEdit(self.tab_3)
        self.waterEmissEdit.setObjectName("waterEmissEdit")
        self.gridLayout_2.addWidget(self.waterEmissEdit, 8, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        self.label_59.setObjectName("label_59")
        self.gridLayout_2.addWidget(self.label_59, 8, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.tab_3)
        self.label_72.setObjectName("label_72")
        self.gridLayout_2.addWidget(self.label_72, 9, 0, 1, 1)
        self.sandEmissEdit = QtWidgets.QLineEdit(self.tab_3)
        self.sandEmissEdit.setObjectName("sandEmissEdit")
        self.gridLayout_2.addWidget(self.sandEmissEdit, 11, 1, 1, 1)
        self.soilEmissEdit = QtWidgets.QLineEdit(self.tab_3)
        self.soilEmissEdit.setObjectName("soilEmissEdit")
        self.gridLayout_2.addWidget(self.soilEmissEdit, 10, 1, 1, 1)
        self.vegEmissEdit = QtWidgets.QLineEdit(self.tab_3)
        self.vegEmissEdit.setObjectName("vegEmissEdit")
        self.gridLayout_2.addWidget(self.vegEmissEdit, 9, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab_3)
        self.label_75.setObjectName("label_75")
        self.gridLayout_2.addWidget(self.label_75, 7, 0, 1, 1)
        self.surfEmissivityEdit = QtWidgets.QLineEdit(self.tab_3)
        self.surfEmissivityEdit.setObjectName("surfEmissivityEdit")
        self.gridLayout_2.addWidget(self.surfEmissivityEdit, 7, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.heightUnitEdit = QtWidgets.QLineEdit(self.tab_2)
        self.heightUnitEdit.setObjectName("heightUnitEdit")
        self.gridLayout_3.addWidget(self.heightUnitEdit, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.flightHeadingEdit = QtWidgets.QLineEdit(self.tab_2)
        self.flightHeadingEdit.setObjectName("flightHeadingEdit")
        self.gridLayout_3.addWidget(self.flightHeadingEdit, 2, 1, 1, 1)
        self.flightAltitudeEdit = QtWidgets.QLineEdit(self.tab_2)
        self.flightAltitudeEdit.setObjectName("flightAltitudeEdit")
        self.gridLayout_3.addWidget(self.flightAltitudeEdit, 1, 1, 1, 1)
        self.meanElevationEdit = QtWidgets.QLineEdit(self.tab_2)
        self.meanElevationEdit.setObjectName("meanElevationEdit")
        self.gridLayout_3.addWidget(self.meanElevationEdit, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cirrusRemovalCombo = QtWidgets.QComboBox(self.tab_4)
        self.cirrusRemovalCombo.setObjectName("cirrusRemovalCombo")
        self.cirrusRemovalCombo.addItem("")
        self.cirrusRemovalCombo.addItem("")
        self.cirrusRemovalCombo.addItem("")
        self.gridLayout_4.addWidget(self.cirrusRemovalCombo, 23, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 10, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 4, 0, 1, 1)
        self.cloudShadowsCombo = QtWidgets.QComboBox(self.tab_4)
        self.cloudShadowsCombo.setObjectName("cloudShadowsCombo")
        self.cloudShadowsCombo.addItem("")
        self.cloudShadowsCombo.addItem("")
        self.cloudShadowsCombo.addItem("")
        self.cloudShadowsCombo.addItem("")
        self.gridLayout_4.addWidget(self.cloudShadowsCombo, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 8, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_4)
        self.label_62.setObjectName("label_62")
        self.gridLayout_4.addWidget(self.label_62, 22, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 20, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_4)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 16, 0, 1, 1)
        self.waterShadowsCombo = QtWidgets.QComboBox(self.tab_4)
        self.waterShadowsCombo.setObjectName("waterShadowsCombo")
        self.waterShadowsCombo.addItem("")
        self.waterShadowsCombo.addItem("")
        self.gridLayout_4.addWidget(self.waterShadowsCombo, 9, 0, 1, 1)
        self.hazeMaskCombo = QtWidgets.QComboBox(self.tab_4)
        self.hazeMaskCombo.setObjectName("hazeMaskCombo")
        self.hazeMaskCombo.addItem("")
        self.hazeMaskCombo.addItem("")
        self.gridLayout_4.addWidget(self.hazeMaskCombo, 15, 0, 1, 1)
        self.visibilityCombo = QtWidgets.QComboBox(self.tab_4)
        self.visibilityCombo.setObjectName("visibilityCombo")
        self.visibilityCombo.addItem("")
        self.visibilityCombo.addItem("")
        self.visibilityCombo.addItem("")
        self.gridLayout_4.addWidget(self.visibilityCombo, 1, 0, 1, 1)
        self.vapourCorrectionCombo = QtWidgets.QComboBox(self.tab_4)
        self.vapourCorrectionCombo.setObjectName("vapourCorrectionCombo")
        self.vapourCorrectionCombo.addItem("")
        self.vapourCorrectionCombo.addItem("")
        self.vapourCorrectionCombo.addItem("")
        self.vapourCorrectionCombo.addItem("")
        self.gridLayout_4.addWidget(self.vapourCorrectionCombo, 5, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 14, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 18, 0, 1, 1)
        self.hazeRemovalCombo = QtWidgets.QComboBox(self.tab_4)
        self.hazeRemovalCombo.setObjectName("hazeRemovalCombo")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.hazeRemovalCombo.addItem("")
        self.gridLayout_4.addWidget(self.hazeRemovalCombo, 7, 0, 1, 1)
        self.shadowAreaEdit = QtWidgets.QLineEdit(self.tab_4)
        self.shadowAreaEdit.setObjectName("shadowAreaEdit")
        self.gridLayout_4.addWidget(self.shadowAreaEdit, 19, 0, 1, 1)
        self.stretchTypeCombo = QtWidgets.QComboBox(self.tab_4)
        self.stretchTypeCombo.setObjectName("stretchTypeCombo")
        self.stretchTypeCombo.addItem("")
        self.stretchTypeCombo.addItem("")
        self.gridLayout_4.addWidget(self.stretchTypeCombo, 21, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_4)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 12, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 6, 0, 1, 1)
        self.hazeCorrectionMaskCombo = QtWidgets.QComboBox(self.tab_4)
        self.hazeCorrectionMaskCombo.setObjectName("hazeCorrectionMaskCombo")
        self.hazeCorrectionMaskCombo.addItem("")
        self.hazeCorrectionMaskCombo.addItem("")
        self.gridLayout_4.addWidget(self.hazeCorrectionMaskCombo, 17, 0, 1, 1)
        self.cloudMaskCombo = QtWidgets.QComboBox(self.tab_4)
        self.cloudMaskCombo.setObjectName("cloudMaskCombo")
        self.cloudMaskCombo.addItem("")
        self.cloudMaskCombo.addItem("")
        self.cloudMaskCombo.addItem("")
        self.gridLayout_4.addWidget(self.cloudMaskCombo, 13, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_4)
        self.label_63.setObjectName("label_63")
        self.gridLayout_4.addWidget(self.label_63, 24, 0, 1, 1)
        self.solarFluxCombo = QtWidgets.QComboBox(self.tab_4)
        self.solarFluxCombo.setObjectName("solarFluxCombo")
        self.solarFluxCombo.addItem("")
        self.solarFluxCombo.addItem("")
        self.gridLayout_4.addWidget(self.solarFluxCombo, 25, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_4)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 2, 0, 1, 1)
        self.castShadowCombo = QtWidgets.QComboBox(self.tab_4)
        self.castShadowCombo.setObjectName("castShadowCombo")
        self.castShadowCombo.addItem("")
        self.castShadowCombo.addItem("")
        self.gridLayout_4.addWidget(self.castShadowCombo, 3, 0, 1, 1)
        self.wv830window1Edit.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.surRefRedThermEdit = QtWidgets.QLineEdit(self.tab_5)
        self.surRefRedThermEdit.setObjectName("surRefRedThermEdit")
        self.gridLayout_5.addWidget(self.surRefRedThermEdit, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 6, 0, 1, 1)
        self.visInterpCombo = QtWidgets.QComboBox(self.tab_5)
        self.visInterpCombo.setObjectName("visInterpCombo")
        self.visInterpCombo.addItem("")
        self.visInterpCombo.addItem("")
        self.gridLayout_5.addWidget(self.visInterpCombo, 1, 1, 1, 1)
        self.surfRefBlueRedEdit = QtWidgets.QLineEdit(self.tab_5)
        self.surfRefBlueRedEdit.setObjectName("surfRefBlueRedEdit")
        self.gridLayout_5.addWidget(self.surfRefBlueRedEdit, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 7, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 5, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 1, 0, 1, 1)
        self.brdfCorrectionCombo = QtWidgets.QComboBox(self.tab_6)
        self.brdfCorrectionCombo.setObjectName("brdfCorrectionCombo")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.brdfCorrectionCombo.addItem("")
        self.gridLayout_6.addWidget(self.brdfCorrectionCombo, 1, 1, 1, 1)
        self.iluAngleEdit = QtWidgets.QLineEdit(self.tab_6)
        self.iluAngleEdit.setObjectName("iluAngleEdit")
        self.gridLayout_6.addWidget(self.iluAngleEdit, 3, 1, 1, 1)
        self.brdfCorrBoundsEdit = QtWidgets.QLineEdit(self.tab_6)
        self.brdfCorrBoundsEdit.setObjectName("brdfCorrBoundsEdit")
        self.gridLayout_6.addWidget(self.brdfCorrBoundsEdit, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 6, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 8, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 7, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_7.addWidget(self.label_61, 9, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_7)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 6, 0, 1, 1)
        self.a2Edit = QtWidgets.QLineEdit(self.tab_7)
        self.a2Edit.setObjectName("a2Edit")
        self.gridLayout_7.addWidget(self.a2Edit, 4, 1, 1, 1)
        self.a1Edit = QtWidgets.QLineEdit(self.tab_7)
        self.a1Edit.setObjectName("a1Edit")
        self.gridLayout_7.addWidget(self.a1Edit, 3, 1, 1, 1)
        self.aEdit = QtWidgets.QLineEdit(self.tab_7)
        self.aEdit.setObjectName("aEdit")
        self.gridLayout_7.addWidget(self.aEdit, 6, 1, 1, 1)
        self.a0Edit = QtWidgets.QLineEdit(self.tab_7)
        self.a0Edit.setObjectName("a0Edit")
        self.gridLayout_7.addWidget(self.a0Edit, 2, 1, 1, 1)
        self.bEdit = QtWidgets.QLineEdit(self.tab_7)
        self.bEdit.setObjectName("bEdit")
        self.gridLayout_7.addWidget(self.bEdit, 7, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_7)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 1, 0, 1, 1)
        self.cEdit = QtWidgets.QLineEdit(self.tab_7)
        self.cEdit.setObjectName("cEdit")
        self.gridLayout_7.addWidget(self.cEdit, 8, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 11, 1, 1, 1)
        self.wvModelCombo = QtWidgets.QComboBox(self.tab_7)
        self.wvModelCombo.setObjectName("wvModelCombo")
        self.wvModelCombo.addItem("")
        self.wvModelCombo.addItem("")
        self.wvModelCombo.addItem("")
        self.gridLayout_7.addWidget(self.wvModelCombo, 10, 1, 1, 1)
        self.useLaiCombo = QtWidgets.QComboBox(self.tab_7)
        self.useLaiCombo.setObjectName("useLaiCombo")
        self.useLaiCombo.addItem("")
        self.useLaiCombo.addItem("")
        self.gridLayout_7.addWidget(self.useLaiCombo, 1, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_52 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_8.addWidget(self.label_56, 7, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_8)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_8.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_8)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_8.addWidget(self.label_57, 8, 0, 1, 1)
        self.wv1130RightWindow1Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130RightWindow1Edit.setObjectName("wv1130RightWindow1Edit")
        self.gridLayout_8.addWidget(self.wv1130RightWindow1Edit, 9, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_8)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_8.addWidget(self.label_58, 9, 0, 1, 1)
        self.wv830LeftWindow1Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830LeftWindow1Edit.setObjectName("wv830LeftWindow1Edit")
        self.gridLayout_8.addWidget(self.wv830LeftWindow1Edit, 1, 1, 1, 1)
        self.wv1130LeftWindow1Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130LeftWindow1Edit.setObjectName("wv1130LeftWindow1Edit")
        self.gridLayout_8.addWidget(self.wv1130LeftWindow1Edit, 8, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_8)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 2, 0, 1, 1)
        self.wv830RightWindow1Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830RightWindow1Edit.setObjectName("wv830RightWindow1Edit")
        self.gridLayout_8.addWidget(self.wv830RightWindow1Edit, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 14, 1, 1, 1)
        self.wv830AbsorptionLeftEdit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830AbsorptionLeftEdit.setObjectName("wv830AbsorptionLeftEdit")
        self.gridLayout_8.addWidget(self.wv830AbsorptionLeftEdit, 3, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_8)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 1, 0, 1, 1)
        self.wv1130AbsorptionRightEdit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130AbsorptionRightEdit.setObjectName("wv1130AbsorptionRightEdit")
        self.gridLayout_8.addWidget(self.wv1130AbsorptionRightEdit, 11, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab_8)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_8.addWidget(self.label_68, 10, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_8)
        self.label_66.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_8.addWidget(self.label_66, 5, 0, 1, 1)
        self.wv830AbsorptionRightEdit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830AbsorptionRightEdit.setObjectName("wv830AbsorptionRightEdit")
        self.gridLayout_8.addWidget(self.wv830AbsorptionRightEdit, 4, 1, 1, 1)
        self.wv1130AbsorptionLeftEdit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130AbsorptionLeftEdit.setObjectName("wv1130AbsorptionLeftEdit")
        self.gridLayout_8.addWidget(self.wv1130AbsorptionLeftEdit, 10, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_8)
        self.label_65.setObjectName("label_65")
        self.gridLayout_8.addWidget(self.label_65, 4, 0, 1, 1)
        self.wv830RightWindow2Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830RightWindow2Edit.setObjectName("wv830RightWindow2Edit")
        self.gridLayout_8.addWidget(self.wv830RightWindow2Edit, 6, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab_8)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_8.addWidget(self.label_69, 11, 0, 1, 1)
        self.wv830LeftWindow2Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv830LeftWindow2Edit.setObjectName("wv830LeftWindow2Edit")
        self.gridLayout_8.addWidget(self.wv830LeftWindow2Edit, 5, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab_8)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_8.addWidget(self.label_71, 13, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab_8)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 12, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.tab_8)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_8.addWidget(self.label_67, 6, 0, 1, 1)
        self.wv1130LeftWindow2Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130LeftWindow2Edit.setObjectName("wv1130LeftWindow2Edit")
        self.gridLayout_8.addWidget(self.wv1130LeftWindow2Edit, 12, 1, 1, 1)
        self.wv1130RightWindow2Edit = QtWidgets.QLineEdit(self.tab_8)
        self.wv1130RightWindow2Edit.setObjectName("wv1130RightWindow2Edit")
        self.gridLayout_8.addWidget(self.wv1130RightWindow2Edit, 13, 1, 1, 1)
        self.wv830window1Edit.addTab(self.tab_8, "")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.wv830window1Edit)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_inn = QtWidgets.QAction(MainWindow)
        self.actionLoad_inn.setObjectName("actionLoad_inn")
        self.actionExport_inn = QtWidgets.QAction(MainWindow)
        self.actionExport_inn.setObjectName("actionExport_inn")
        self.menuFile.addAction(self.actionLoad_inn)
        self.menuFile.addAction(self.actionExport_inn)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.wv830window1Edit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INN File Reader"))
        self.label.setText(_translate("MainWindow", "File Name:"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.label_5.setText(_translate("MainWindow", "Sensor"))
        self.label_7.setText(_translate("MainWindow", "Calibration File"))
        self.label_8.setText(_translate("MainWindow", "Scan Angle File"))
        self.label_3.setText(_translate("MainWindow", "Elevation File"))
        self.label_4.setText(_translate("MainWindow", "Slope File"))
        self.label_6.setText(_translate("MainWindow", "Aspect File"))
        self.label_9.setText(_translate("MainWindow", "Skyview File"))
        self.label_16.setText(_translate("MainWindow", "Atm Database"))
        self.label_10.setText(_translate("MainWindow", "Solar Zenith"))
        self.label_11.setText(_translate("MainWindow", "Solar Azimuth"))
        self.label_45.setText(_translate("MainWindow", "Water Vapour Pressure at Ref. Elevation"))
        self.label_44.setText(_translate("MainWindow", "Temperature Gradient (Degrees C per 1m Height)"))
        self.label_46.setText(_translate("MainWindow", "Scale Height of Water Vapour"))
        self.label_42.setText(_translate("MainWindow", "Air Temperature at Ref. Elevation"))
        self.label_43.setText(_translate("MainWindow", "Reference Elevation"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab), _translate("MainWindow", "Solar and Weather"))
        self.label_12.setText(_translate("MainWindow", "Pixel Size (m)"))
        self.label_13.setText(_translate("MainWindow", "Scale Factor"))
        self.label_22.setText(_translate("MainWindow", "Adjacency Range"))
        self.label_60.setText(_translate("MainWindow", "Gain"))
        self.label_23.setText(_translate("MainWindow", "Visibility"))
        self.label_74.setText(_translate("MainWindow", "Sand"))
        self.label_21.setText(_translate("MainWindow", "Surface Emissivities"))
        self.label_73.setText(_translate("MainWindow", "Soil"))
        self.label_59.setText(_translate("MainWindow", "Water"))
        self.label_72.setText(_translate("MainWindow", "Vegetation"))
        self.label_75.setText(_translate("MainWindow", "Other"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_3), _translate("MainWindow", "Image"))
        self.label_17.setText(_translate("MainWindow", "Avg. Flight Altitude"))
        self.label_18.setText(_translate("MainWindow", "Avg. Flight Heading"))
        self.label_15.setText(_translate("MainWindow", "Mean Elevation (Flat Terrain Only)"))
        self.label_14.setText(_translate("MainWindow", "Height Unit"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_2), _translate("MainWindow", "Height"))
        self.cirrusRemovalCombo.setItemText(0, _translate("MainWindow", "0"))
        self.cirrusRemovalCombo.setItemText(1, _translate("MainWindow", "1"))
        self.cirrusRemovalCombo.setItemText(2, _translate("MainWindow", "-1"))
        self.label_27.setText(_translate("MainWindow", "Cloud Shadows (0 = none, 1 = output as DN image, 2 = output as reflectance, 3 = output as both)"))
        self.label_24.setText(_translate("MainWindow", "Water Vapour Correction (0 = no correction, 1 = 940nm band region, 2 = 1130nm band region, 3 = 940nm and 1130nm band region)"))
        self.cloudShadowsCombo.setItemText(0, _translate("MainWindow", "0"))
        self.cloudShadowsCombo.setItemText(1, _translate("MainWindow", "1"))
        self.cloudShadowsCombo.setItemText(2, _translate("MainWindow", "2"))
        self.cloudShadowsCombo.setItemText(3, _translate("MainWindow", "3"))
        self.label_26.setText(_translate("MainWindow", "Water Shadows (0 = excluded from de-shadowing, 1 = included in de-shadowing)"))
        self.label_62.setText(_translate("MainWindow", "Cirrus Removal (0 = disabled, 1 = enabled, -1 = forced"))
        self.label_51.setText(_translate("MainWindow", "Stretch Type (1 = linear, 2 = exponential)"))
        self.label_20.setText(_translate("MainWindow", "Visibility (0 = constant, 1 = variable based on dark reference, -1 = variable with tiling)"))
        self.label_48.setText(_translate("MainWindow", "Haze Correction Limits (1 = thin to medium, 2 = thin to thick)"))
        self.waterShadowsCombo.setItemText(0, _translate("MainWindow", "0"))
        self.waterShadowsCombo.setItemText(1, _translate("MainWindow", "1"))
        self.hazeMaskCombo.setItemText(0, _translate("MainWindow", "1"))
        self.hazeMaskCombo.setItemText(1, _translate("MainWindow", "2"))
        self.visibilityCombo.setItemText(0, _translate("MainWindow", "0"))
        self.visibilityCombo.setItemText(1, _translate("MainWindow", "1"))
        self.visibilityCombo.setItemText(2, _translate("MainWindow", "-1"))
        self.vapourCorrectionCombo.setItemText(0, _translate("MainWindow", "0"))
        self.vapourCorrectionCombo.setItemText(1, _translate("MainWindow", "1"))
        self.vapourCorrectionCombo.setItemText(2, _translate("MainWindow", "2"))
        self.vapourCorrectionCombo.setItemText(3, _translate("MainWindow", "3"))
        self.label_47.setText(_translate("MainWindow", "Haze Mask (1 = small, 2 = large)"))
        self.label_50.setText(_translate("MainWindow", "Shadow Area Threshold"))
        self.hazeRemovalCombo.setItemText(0, _translate("MainWindow", "0"))
        self.hazeRemovalCombo.setItemText(1, _translate("MainWindow", "1"))
        self.hazeRemovalCombo.setItemText(2, _translate("MainWindow", "2"))
        self.hazeRemovalCombo.setItemText(3, _translate("MainWindow", "3"))
        self.hazeRemovalCombo.setItemText(4, _translate("MainWindow", "4"))
        self.hazeRemovalCombo.setItemText(5, _translate("MainWindow", "-1"))
        self.hazeRemovalCombo.setItemText(6, _translate("MainWindow", "-2"))
        self.hazeRemovalCombo.setItemText(7, _translate("MainWindow", "-3"))
        self.stretchTypeCombo.setItemText(0, _translate("MainWindow", "1"))
        self.stretchTypeCombo.setItemText(1, _translate("MainWindow", "2"))
        self.label_49.setText(_translate("MainWindow", "Cloud Shadow Mask (1 = small, 2 = medium, 3 = large)"))
        self.label_25.setText(_translate("MainWindow", "Haze Removal (0 = none, 1 = land, 2 = water, 3 = land & water, 4 = water glint removal,  -1 = land w/o quality check, -2 = forced water, -3 = forced land)"))
        self.hazeCorrectionMaskCombo.setItemText(0, _translate("MainWindow", "1"))
        self.hazeCorrectionMaskCombo.setItemText(1, _translate("MainWindow", "2"))
        self.cloudMaskCombo.setItemText(0, _translate("MainWindow", "1"))
        self.cloudMaskCombo.setItemText(1, _translate("MainWindow", "2"))
        self.cloudMaskCombo.setItemText(2, _translate("MainWindow", "3"))
        self.label_63.setText(_translate("MainWindow", "Solar Flux at Ground (0 = disabled, 1 = enabled) "))
        self.solarFluxCombo.setItemText(0, _translate("MainWindow", "0"))
        self.solarFluxCombo.setItemText(1, _translate("MainWindow", "1"))
        self.label_64.setText(_translate("MainWindow", "DEM Cast Shadow (0 = none, 1 = used)"))
        self.castShadowCombo.setItemText(0, _translate("MainWindow", "0"))
        self.castShadowCombo.setItemText(1, _translate("MainWindow", "1"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_4), _translate("MainWindow", "Haze and Shadows"))
        self.label_28.setText(_translate("MainWindow", "Visibility Interpolation (0 = average vis., 1 = triangular interpolation)"))
        self.label_19.setText(_translate("MainWindow", "Surface Reflectance Ratio of Red to 2200nm band"))
        self.label_29.setText(_translate("MainWindow", "Surface Reflectance Ratio of Blue to Red Bands"))
        self.visInterpCombo.setItemText(0, _translate("MainWindow", "0"))
        self.visInterpCombo.setItemText(1, _translate("MainWindow", "1"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_5), _translate("MainWindow", "Spectral Ratios"))
        self.label_32.setText(_translate("MainWindow", "BRDF Correction Factor: Lower Boundary"))
        self.label_31.setText(_translate("MainWindow", "Illumination Angle Threshold"))
        self.label_30.setText(_translate("MainWindow", "BRDF Correction Type"))
        self.brdfCorrectionCombo.setItemText(0, _translate("MainWindow", "0 - No Corrections"))
        self.brdfCorrectionCombo.setItemText(1, _translate("MainWindow", "1 - Correction with Cosine of Local Solar Zenith Angle"))
        self.brdfCorrectionCombo.setItemText(2, _translate("MainWindow", "2 - Correction with sqrt(Cosine) of Local Solar Zenith Angle"))
        self.brdfCorrectionCombo.setItemText(3, _translate("MainWindow", "11 - Correction with Cosine of Local Solar Zenith Angle with Soil - Sand - Veg Differentiation"))
        self.brdfCorrectionCombo.setItemText(4, _translate("MainWindow", "12 - Stronger Version of 11 - Recommended"))
        self.brdfCorrectionCombo.setItemText(5, _translate("MainWindow", "21 - Correction with sqrt(Cosine) of Local Solar Zenith Angle with Soil - Sand - Veg Differentiation"))
        self.brdfCorrectionCombo.setItemText(6, _translate("MainWindow", "22 - Stronger Version of 21 - Recommended"))
        self.brdfCorrectionCombo.setItemText(7, _translate("MainWindow", "30 - IRC Topographic Correction"))
        self.brdfCorrectionCombo.setItemText(8, _translate("MainWindow", "40 - Topograpic Compensation with C-Correction Method"))
        self.brdfCorrectionCombo.setItemText(9, _translate("MainWindow", "41 - Topographic Compensation with SE (Statistical Emperical) Method"))
        self.brdfCorrectionCombo.setItemText(10, _translate("MainWindow", "50 - Topographic Compensation with Lambert + C Method"))
        self.brdfCorrectionCombo.setItemText(11, _translate("MainWindow", "51 - Topographic Compensation with Lambert + SE Method"))
        self.brdfCorrectionCombo.setItemText(12, _translate("MainWindow", "52 - Topographic Compensation with Lambert + SE (Variant) Method"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_6), _translate("MainWindow", "BRDF Parameters"))
        self.label_35.setText(_translate("MainWindow", "A0:"))
        self.label_41.setText(_translate("MainWindow", "C:"))
        self.label_40.setText(_translate("MainWindow", "B:"))
        self.label_61.setText(_translate("MainWindow", "Water Vapour Model"))
        self.label_37.setText(_translate("MainWindow", "A2:"))
        self.label_36.setText(_translate("MainWindow", "A1:"))
        self.label_39.setText(_translate("MainWindow", "A:"))
        self.label_38.setText(_translate("MainWindow", "FPAR Model Parameters"))
        self.label_34.setText(_translate("MainWindow", "Use LAI? (0 = no, 1 = yes)"))
        self.label_33.setText(_translate("MainWindow", "LAI Model Parameters"))
        self.wvModelCombo.setItemText(0, _translate("MainWindow", "0 - None"))
        self.wvModelCombo.setItemText(1, _translate("MainWindow", "1 - No Band Regression"))
        self.wvModelCombo.setItemText(2, _translate("MainWindow", "2 - Band Regression"))
        self.useLaiCombo.setItemText(0, _translate("MainWindow", "0"))
        self.useLaiCombo.setItemText(1, _translate("MainWindow", "1"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_7), _translate("MainWindow", "Model Parameters"))
        self.label_52.setText(_translate("MainWindow", "940nm Retrieval"))
        self.label_56.setText(_translate("MainWindow", "1130nm Retrieval"))
        self.label_55.setText(_translate("MainWindow", "Left Absorption Channel (920 - 970):"))
        self.label_57.setText(_translate("MainWindow", "Left Window (1050 - 1090):"))
        self.label_58.setText(_translate("MainWindow", "Right Window (1050 - 1090):"))
        self.label_54.setText(_translate("MainWindow", "Right window (850 - 890):"))
        self.label_53.setText(_translate("MainWindow", "Left Window (850 - 890):"))
        self.label_68.setText(_translate("MainWindow", "Left Absorption Channel (1110 - 1155):"))
        self.label_66.setText(_translate("MainWindow", "Left Window (1000 - 1040):"))
        self.label_65.setText(_translate("MainWindow", "Right Absorption Channel (920 - 970):"))
        self.label_69.setText(_translate("MainWindow", "Right Absorption Channel (1110 - 1155):"))
        self.label_71.setText(_translate("MainWindow", "Right Window (1200 - 1250):"))
        self.label_70.setText(_translate("MainWindow", "Left Window (1200 - 1250):"))
        self.label_67.setText(_translate("MainWindow", "Right Window (1000 - 1040):"))
        self.wv830window1Edit.setTabText(self.wv830window1Edit.indexOf(self.tab_8), _translate("MainWindow", "Vapour Retrieval"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_inn.setText(_translate("MainWindow", "Load .inn"))
        self.actionExport_inn.setText(_translate("MainWindow", "Export .inn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

